### ISSUE TITLE
Лабораторная № 6 Вопросы

### ISSUE THREAD

**Issue by readysloth** [Leeoree/ACS_labs#2]
Ребят, расскажите, как работает устройство Даффа и зачем оно было нужно :)

**Comment by Leeoree** [comment]
Устройство Даффа реализуется через совместное использование switch, все case-ы которого последовательно переходят друг в друга, и while, покрывающего часть case-ов и отмеряющего единицы копируемой памяти(байты. например). Устройство Даффа фактически является программным методом копирования из одного участка памяти в другой, применялся для уменьшения количества сравнений и ветвлений.
